export interface PresentielClass {
  id: number;
  niveau: string;
  ageCondition: string;
  horaire: string;
  audience: "enfant" | "adulte";
  type: "mixte" | "femme";
  jour: "lundi" | "mardi" | "mercredi" | "samedi" | "dimanche";
  periode: "matin" | "après-midi" | "soir";
  planId: string;
  slotKey: string;
  niveauKey: string;
}

export const PRESENTIEL_CLASSES: PresentielClass[] = [
  // --- ENFANTS (1 à 25) ---
  {
    id: 1,
    niveau: "Préparatoire 1ère année",
    ageCondition: "4-6 ans",
    horaire: "MERCREDI",
    audience: "enfant",
    type: "mixte",
    jour: "mercredi",
    periode: "après-midi",
    planId: "presentiel-global",
    slotKey: "mercredi",
    niveauKey: "maternel_1"
  },
  {
    id: 2,
    niveau: "Préparatoire 1ère année",
    ageCondition: "4-6 ans",
    horaire: "SAMEDI MATIN",
    audience: "enfant",
    type: "mixte",
    jour: "samedi",
    periode: "matin",
    planId: "presentiel-global",
    slotKey: "samedi",
    niveauKey: "maternel_1"
  },
  {
    id: 3,
    niveau: "Préparatoire 1ère année",
    ageCondition: "4-6 ans",
    horaire: "SAMEDI A-M",
    audience: "enfant",
    type: "mixte",
    jour: "samedi",
    periode: "après-midi",
    planId: "presentiel-global",
    slotKey: "samedi",
    niveauKey: "maternel_1"
  },
  {
    id: 4,
    niveau: "Préparatoire 1ère année",
    ageCondition: "4-6 ans",
    horaire: "DIMANCHE MATIN",
    audience: "enfant",
    type: "mixte",
    jour: "dimanche",
    periode: "matin",
    planId: "presentiel-global",
    slotKey: "dimanche",
    niveauKey: "maternel_1"
  },
  {
    id: 5,
    niveau: "Préparatoire 2ème année",
    ageCondition: "5-6 ans",
    horaire: "MERCREDI",
    audience: "enfant",
    type: "mixte",
    jour: "mercredi",
    periode: "après-midi",
    planId: "presentiel-global",
    slotKey: "mercredi",
    niveauKey: "maternel_2"
  },
  {
    id: 6,
    niveau: "Préparatoire 2ème année",
    ageCondition: "5-6 ans",
    horaire: "SAMEDI MATIN",
    audience: "enfant",
    type: "mixte",
    jour: "samedi",
    periode: "matin",
    planId: "presentiel-global",
    slotKey: "samedi",
    niveauKey: "maternel_2"
  },
  {
    id: 7,
    niveau: "Préparatoire 2ème année",
    ageCondition: "5-6 ans",
    horaire: "DIMANCHE MATIN",
    audience: "enfant",
    type: "mixte",
    jour: "dimanche",
    periode: "matin",
    planId: "presentiel-global",
    slotKey: "dimanche",
    niveauKey: "maternel_2"
  },
  {
    id: 8,
    niveau: "Élémentaire Débutant 1",
    ageCondition: "7-14 ans",
    horaire: "MERCREDI",
    audience: "enfant",
    type: "mixte",
    jour: "mercredi",
    periode: "après-midi",
    planId: "presentiel-global",
    slotKey: "mercredi",
    niveauKey: "elementaire_1"
  },
  {
    id: 9,
    niveau: "Élémentaire Débutant 1",
    ageCondition: "7-14 ans",
    horaire: "SAMEDI MATIN",
    audience: "enfant",
    type: "mixte",
    jour: "samedi",
    periode: "matin",
    planId: "presentiel-global",
    slotKey: "samedi",
    niveauKey: "elementaire_1"
  },
  {
    id: 10,
    niveau: "Élémentaire Débutant 1",
    ageCondition: "7-14 ans",
    horaire: "SAMEDI A-M",
    audience: "enfant",
    type: "mixte",
    jour: "samedi",
    periode: "après-midi",
    planId: "presentiel-global",
    slotKey: "samedi",
    niveauKey: "elementaire_1"
  },
  {
    id: 11,
    niveau: "Élémentaire Débutant 1",
    ageCondition: "7-14 ans",
    horaire: "DIMANCHE MATIN",
    audience: "enfant",
    type: "mixte",
    jour: "dimanche",
    periode: "matin",
    planId: "presentiel-global",
    slotKey: "dimanche",
    niveauKey: "elementaire_1"
  },
  {
    id: 12,
    niveau: "Élémentaire Débutant 1",
    ageCondition: "7-14 ans",
    horaire: "DIMANCHE A-M",
    audience: "enfant",
    type: "mixte",
    jour: "dimanche",
    periode: "après-midi",
    planId: "presentiel-global",
    slotKey: "dimanche",
    niveauKey: "elementaire_1"
  },
  {
    id: 13,
    niveau: "Élémentaire 1+",
    ageCondition: "NON débutant",
    horaire: "MERCREDI",
    audience: "enfant",
    type: "mixte",
    jour: "mercredi",
    periode: "après-midi",
    planId: "presentiel-global",
    slotKey: "mercredi",
    niveauKey: "elementaire_1_plus"
  },
  {
    id: 14,
    niveau: "Élémentaire 1+",
    ageCondition: "NON débutant",
    horaire: "SAMEDI MATIN",
    audience: "enfant",
    type: "mixte",
    jour: "samedi",
    periode: "matin",
    planId: "presentiel-global",
    slotKey: "samedi",
    niveauKey: "elementaire_1_plus"
  },
  {
    id: 15,
    niveau: "Élémentaire 1+",
    ageCondition: "NON débutant",
    horaire: "SAMEDI A-M",
    audience: "enfant",
    type: "mixte",
    jour: "samedi",
    periode: "après-midi",
    planId: "presentiel-global",
    slotKey: "samedi",
    niveauKey: "elementaire_1_plus"
  },
  {
    id: 16,
    niveau: "Élémentaire 1+",
    ageCondition: "NON débutant",
    horaire: "DIMANCHE MATIN",
    audience: "enfant",
    type: "mixte",
    jour: "dimanche",
    periode: "matin",
    planId: "presentiel-global",
    slotKey: "dimanche",
    niveauKey: "elementaire_1_plus"
  },
  {
    id: 17,
    niveau: "Élémentaire 1+",
    ageCondition: "NON débutant",
    horaire: "DIMANCHE A-M",
    audience: "enfant",
    type: "mixte",
    jour: "dimanche",
    periode: "après-midi",
    planId: "presentiel-global",
    slotKey: "dimanche",
    niveauKey: "elementaire_1_plus"
  },
  {
    id: 18,
    niveau: "Élémentaire 2 et 2+",
    ageCondition: "7-14 ans",
    horaire: "MERCREDI",
    audience: "enfant",
    type: "mixte",
    jour: "mercredi",
    periode: "après-midi",
    planId: "presentiel-global",
    slotKey: "mercredi",
    niveauKey: "elementaire_2"
  },
  {
    id: 19,
    niveau: "Élémentaire 2",
    ageCondition: "7-14 ans",
    horaire: "DIMANCHE MATIN",
    audience: "enfant",
    type: "mixte",
    jour: "dimanche",
    periode: "matin",
    planId: "presentiel-global",
    slotKey: "dimanche",
    niveauKey: "elementaire_2"
  },
  {
    id: 20,
    niveau: "Élémentaire 2",
    ageCondition: "7-14 ans",
    horaire: "DIMANCHE A-M",
    audience: "enfant",
    type: "mixte",
    jour: "dimanche",
    periode: "après-midi",
    planId: "presentiel-global",
    slotKey: "dimanche",
    niveauKey: "elementaire_2"
  },
  {
    id: 21,
    niveau: "Élémentaire 2+",
    ageCondition: "7-14 ans",
    horaire: "DIMANCHE A-M",
    audience: "enfant",
    type: "mixte",
    jour: "dimanche",
    periode: "après-midi",
    planId: "presentiel-global",
    slotKey: "dimanche",
    niveauKey: "elementaire_2_plus"
  },
  {
    id: 22,
    niveau: "Élémentaire 3",
    ageCondition: "7-14 ans",
    horaire: "DIMANCHE A-M",
    audience: "enfant",
    type: "mixte",
    jour: "dimanche",
    periode: "après-midi",
    planId: "presentiel-global",
    slotKey: "dimanche",
    niveauKey: "elementaire_3"
  },
  {
    id: 23,
    niveau: "Élémentaire 3 et 3+",
    ageCondition: "7-12 ans",
    horaire: "MERCREDI",
    audience: "enfant",
    type: "mixte",
    jour: "mercredi",
    periode: "après-midi",
    planId: "presentiel-global",
    slotKey: "mercredi",
    niveauKey: "elementaire_3"
  },
  {
    id: 24,
    niveau: "Élémentaire 4",
    ageCondition: "7-14 ans",
    horaire: "DIMANCHE A-M",
    audience: "enfant",
    type: "mixte",
    jour: "dimanche",
    periode: "après-midi",
    planId: "presentiel-global",
    slotKey: "dimanche",
    niveauKey: "elementaire_4"
  },
  {
    id: 25,
    niveau: "Élémentaire 5",
    ageCondition: "7-15 ans",
    horaire: "DIMANCHE A-M",
    audience: "enfant",
    type: "mixte",
    jour: "dimanche",
    periode: "après-midi",
    planId: "presentiel-global",
    slotKey: "dimanche",
    niveauKey: "elementaire_5"
  },

  // --- FEMMES (26 à 31) ---
  {
    id: 26,
    niveau: "Femme débutante ARABE + TAJWID",
    ageCondition: "Femme",
    horaire: "Dimanche matin",
    audience: "adulte",
    type: "femme",
    jour: "dimanche",
    periode: "matin",
    planId: "presentiel-global",
    slotKey: "dimanche",
    niveauKey: "femme_debutante"
  },
  {
    id: 27,
    niveau: "Femme débutante TAJWID SEUL",
    ageCondition: "Femme",
    horaire: "Dimanche matin",
    audience: "adulte",
    type: "femme",
    jour: "dimanche",
    periode: "matin",
    planId: "presentiel-global",
    slotKey: "dimanche",
    niveauKey: "femme_debutante"
  },
  {
    id: 28,
    niveau: "Femme débutante ARABE SEUL",
    ageCondition: "Femme",
    horaire: "Dimanche matin",
    audience: "adulte",
    type: "femme",
    jour: "dimanche",
    periode: "matin",
    planId: "presentiel-global",
    slotKey: "dimanche",
    niveauKey: "femme_debutante"
  },
  {
    id: 29,
    niveau: "Femme intermédiaire ARABE",
    ageCondition: "Femme",
    horaire: "Samedi matin",
    audience: "adulte",
    type: "femme",
    jour: "samedi",
    periode: "matin",
    planId: "presentiel-global",
    slotKey: "samedi",
    niveauKey: "femme_intermediaire"
  },
  {
    id: 30,
    niveau: "Femme intermédiaire TAJWID",
    ageCondition: "Femme",
    horaire: "Samedi matin",
    audience: "adulte",
    type: "femme",
    jour: "samedi",
    periode: "matin",
    planId: "presentiel-global",
    slotKey: "samedi",
    niveauKey: "femme_intermediaire"
  },
  {
    id: 31,
    niveau: "Femme intermédiaire ARABE + TAJ",
    ageCondition: "Femme",
    horaire: "Samedi après-midi",
    audience: "adulte",
    type: "femme",
    jour: "samedi",
    periode: "après-midi",
    planId: "presentiel-global",
    slotKey: "samedi",
    niveauKey: "femme_intermediaire"
  }
];
