#!/bin/sh

echo "✅ Lancement des tests unitaires (Jest)..."
echo "⏳ Premier lancement : Next compile les tests, ça peut prendre 1 à 2 min."
CI=true npm test -- --colors --maxWorkers=2

if [ $? -ne 0 ]; then
  echo "❌ Le push a été bloqué car les tests unitaires ont échoué."
  exit 1
fi

echo "🔄 Lancement du test d'intégrité de la base de données..."
node scripts/test-db-mapping.mjs

if [ $? -ne 0 ]; then
  echo "❌ Le push a été bloqué car des erreurs d'intégrité ont été trouvées dans la base de données."
  exit 1
fi
